 export  const CartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM_CART',
    DELETE_ITEM:'DELETE_ITEM',
    CLEAR_CART:'CLEAR_CART'
}
 